version: 1

input:
  # Paths in this file are resolved relative to this YAML file.
  file: ../reference_files/RoboSprayer_3500Kg_Electric_12kph_Batt_50kW_Mot_63RPM_Susp_Cool_Rough_Grad_Discharge.csv
  strict: true

configs:
  channel_selection: channel_selection_example.yaml
  math_channels: math_channels_example.yaml
  statistics: statistics_example.yaml
  plotting: plotting_example.yaml
  excel_statistics: statistics_excel_report.yaml
  excel_report: excel_report_example.yaml
  powerpoint_report: powerpoint_report_example.yaml

output:
  root_dir: ../outputs/end_to_end
  clean_before_run: true
