"""VSM engineering data post-processing package."""

from .version import __version__

from .channel_manager import (
    ChannelSelectionConfig,
    ChannelSelectionResult,
    SelectionOutputOptions,
    export_channel_selection,
    load_selection_config,
    select_channels,
)
from .importer import ImportOptions, inspect_data_file, load_data_file
from .excel_report_engine import ExcelReportConfig, ExcelReportResult, generate_excel_report, load_excel_report_config
from .duty_cycle import (
    DutyCycleComposition,
    DutyCycleCompositionPlan,
    DutyCyclePartialComposition,
    DutyCyclePhase,
    DutyCycleRowProvenance,
    DutyCycleScenario,
    OpportunityChargeConfig,
    DutyCycleSourceValidation,
    ReportRowRange,
    SourceRowRange,
    WorkbookProfileProviderConfig,
    WorkbookRowProfileProvider,
    ProfileProviderValidation,
    PhaseProfileProvenance,
    build_composition_plan,
    compose_duty_cycle,
    compose_supported_prefix,
    export_composition_plan,
    export_duty_cycle_composition,
    export_partial_composition,
    load_duty_cycle_config,
    load_profile_provider_config,
    validate_source_dataset,
)
from .math_engine import (
    MathChannelDefinition,
    MathChannelsConfig,
    MathChannelsResult,
    MathComparisonDefinition,
    MathComparisonResult,
    MathOutputOptions,
    calculate_math_channels,
    export_math_channels,
    load_math_config,
)
from .models import ChannelInfo, DataInspectionResult, DataQualityReport, ImportedDataset
from .plotting_engine import (
    PlotDefaults,
    PlotDefinition,
    PlotSeriesDefinition,
    PlottingConfig,
    PlottingResult,
    RenderedPlot,
    load_plotting_config,
    render_plots,
)
from .pipeline_engine import PipelineConfig, PipelineResult, PipelineStage, load_pipeline_config, run_pipeline
from .powerpoint_report_engine import (
    PowerPointReportConfig,
    PowerPointReportResult,
    PowerPointSlideDefinition,
    PowerPointTheme,
    build_powerpoint_report,
    generate_powerpoint_report,
    load_powerpoint_report_config,
)
from .statistics_engine import (
    StatisticComparisonDefinition,
    StatisticComparisonResult,
    StatisticDefinition,
    StatisticResult,
    StatisticsConfig,
    StatisticsOutputOptions,
    StatisticsResult,
    calculate_statistics,
    compute_statistic,
    export_statistics,
    load_statistics_config,
)

__all__ = [
    "ChannelInfo",
    "ChannelSelectionConfig",
    "ChannelSelectionResult",
    "DataInspectionResult",
    "DataQualityReport",
    "DutyCycleComposition",
    "DutyCycleCompositionPlan",
    "DutyCyclePartialComposition",
    "DutyCyclePhase",
    "DutyCycleRowProvenance",
    "DutyCycleScenario",
    "OpportunityChargeConfig",
    "DutyCycleSourceValidation",
    "ReportRowRange",
    "SourceRowRange",
    "WorkbookProfileProviderConfig",
    "WorkbookRowProfileProvider",
    "ProfileProviderValidation",
    "PhaseProfileProvenance",
    "ImportedDataset",
    "ImportOptions",
    "ExcelReportConfig",
    "ExcelReportResult",
    "MathChannelDefinition",
    "MathChannelsConfig",
    "MathChannelsResult",
    "MathComparisonDefinition",
    "MathComparisonResult",
    "MathOutputOptions",
    "SelectionOutputOptions",
    "PipelineConfig",
    "PipelineResult",
    "PipelineStage",
    "PowerPointReportConfig",
    "PowerPointReportResult",
    "PowerPointSlideDefinition",
    "PowerPointTheme",
    "PlotDefaults",
    "PlotDefinition",
    "PlotSeriesDefinition",
    "PlottingConfig",
    "PlottingResult",
    "RenderedPlot",
    "StatisticComparisonDefinition",
    "StatisticComparisonResult",
    "StatisticDefinition",
    "StatisticResult",
    "StatisticsConfig",
    "StatisticsOutputOptions",
    "StatisticsResult",
    "calculate_math_channels",
    "generate_excel_report",
    "generate_powerpoint_report",
    "build_powerpoint_report",
    "calculate_statistics",
    "compute_statistic",
    "export_channel_selection",
    "export_math_channels",
    "export_statistics",
    "inspect_data_file",
    "load_data_file",
    "build_composition_plan",
    "compose_duty_cycle",
    "compose_supported_prefix",
    "export_composition_plan",
    "export_duty_cycle_composition",
    "export_partial_composition",
    "load_duty_cycle_config",
    "load_profile_provider_config",
    "validate_source_dataset",
    "load_excel_report_config",
    "load_pipeline_config",
    "load_powerpoint_report_config",
    "run_pipeline",
    "load_math_config",
    "load_plotting_config",
    "load_selection_config",
    "load_statistics_config",
    "render_plots",
    "select_channels",
]

